version: '3.8'

services:
  transaction-consumer:
    image: hassansena/transaction-consumer:latest
    container_name: transaction-consumer
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xmx512m
    restart: unless-stopped
    networks:
      - app-network

  # Exemplo com banco de dados (adicione se necessário)
  # postgres:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_DB: meudb
  #     POSTGRES_USER: usuario
  #     POSTGRES_PASSWORD: senha
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

# volumes:
#   postgres_data: